image: registry.gitlab.com/mydropwizard/lando-docker

variables:
  DOCKER_HOST: 'tcp://docker:2375/'

services:
  - docker:dind

stages:
  - build

test:
  stage: build
  script:
    - .gitlab-ci/test.sh
  parallel:
    matrix:
      - UPGRADE: 'no-upgrade'
        PHP_VERSION:
          - '7.4'
          - '7.3'
      - UPGRADE:
          - '2.0.0-alpha16'
        PHP_VERSION: '7.4'
  artifacts:
    when: on_failure
    name: "screenshots-${CI_BUILD_STAGE}-${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    paths:
      - drupal/web/sites/default/files/screenshots

push:
  stage: build
  image: php:7.4
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -yq wget zip unzip git libpng-dev

    # Configure Git.
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"

    # Install PHP extensions.
    - docker-php-ext-install gd

    # Install composer
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"

    # Install splitsh-lite.
    - wget https://github.com/splitsh/lite/releases/download/v1.0.1/lite_linux_amd64.tar.gz
    - tar -zxpf lite_linux_amd64.tar.gz --directory /usr/local/bin/
    - rm lite_linux_amd64.tar.gz
  script:
    # Attach the current commit to its branch.
    - git checkout -b $CI_COMMIT_REF_NAME

    # Push code changes to main Drupal.org repo.
    - mkdir -p ~/.ssh
    - echo "$GIT_DEPLOY_KEY" >> ~/.ssh/id_rsa
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 0700 ~/.ssh
    - chmod 0600 ~/.ssh/id_rsa
    - chmod 0644 ~/.ssh/known_hosts
    - git remote add drupalorg git@git.drupal.org:project/panopoly.git
    - git push drupalorg $CI_COMMIT_REF_NAME

    # Do subtree split and push.
    - php composer.phar install
    - ./vendor/bin/robo subtree-split --push
  only:
    refs:
      - 8.x-2.x
    variables:
      - $GIT_DEPLOY_KEY
      - $SSH_KNOWN_HOSTS

