image: registry.gitlab.com/mydropwizard/lando-docker

variables:
  DOCKER_HOST: 'tcp://docker:2375/'

services:
  - docker:dind

stages:
  - build

test:
  stage: build
  script:
    # GitLab CI checks out the commit unattached from any branch. We need to
    # put it in a branch for the Composer repository to work.
    - git checkout -b $CI_COMMIT_REF_NAME

    # Create new Lando home directory within $CI_SHARED_DIR so that it can be
    # mounted by the docker:dind service.
    - export CI_SHARED_DIR=$(dirname $CI_PROJECT_DIR)
    - cp -r /home/lando $CI_SHARED_DIR/
    - cp .gitlab-ci-global-lando-config.yml $CI_SHARED_DIR/lando/.lando/config.yml
    - export HOME=$CI_SHARED_DIR/lando
    - cd $CI_SHARED_DIR

    # Setup hostname for Panopoly site.
    - echo $(getent hosts docker | awk '{ print $1 }') panopoly-2.docker | sudo tee -a /etc/hosts

    # This is roughly equivalent to:
    #
    #   composer create-project panopoly/panopoly-composer-template:9.x-dev drupal --no-interaction --no-install
    #
    # We don't want to run composer here, because we want Lando to run it,
    # so that, the PHP version used by Lando is used.
    - mkdir drupal
    - curl https://gitlab.com/panopoly/panopoly-composer-template/-/archive/9.x/panopoly-composer-template-9.x.tar.bz2 | tar -xj -C drupal --strip-components=1

    # Use Lando to run composer.
    - cd drupal
    - cat $CI_PROJECT_DIR/.gitlab-ci-lando.yml | sed -e "s,CI_PROJECT_DIR,$CI_PROJECT_DIR,g" > .lando.yml
    # NOTE: the .lando.yml specially mounts the $CI_PROJECT_DIR as /src/panopoly
    # in the appserver, so we can point the repository there.
    - lando start
    - lando composer config repositories.panopoly path /src/panopoly
    - lando composer require "panopoly/panopoly:dev-$CI_COMMIT_REF_NAME as 2.x-dev" --no-update
    - lando composer require drush/drush drupal/diff --no-update
    - lando composer install
    - cd web

    # Install Drupal.
    - lando drush si panopoly --db-url=mysql://drupal9:drupal9@database/drupal9 -y
    - lando drush en -y panopoly_test

    # Check if any modules are overridden.
    - lando drush en -y features diff
    - lando ssh -c 'cd profiles/contrib/panopoly && /app/vendor/bin/robo check:overridden'

    # Run the Behat tests
    - lando ssh -c 'cd profiles/contrib/panopoly/modules/panopoly/panopoly_test/behat && /app/vendor/bin/behat --config behat.lando.yml'

push:
  stage: build
  image: php:7.4
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -yq wget zip unzip git libpng-dev

    # Configure Git.
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"

    # Install PHP extensions.
    - docker-php-ext-install gd

    # Install composer
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"

    # Install splitsh-lite.
    - wget https://github.com/splitsh/lite/releases/download/v1.0.1/lite_linux_amd64.tar.gz
    - tar -zxpf lite_linux_amd64.tar.gz --directory /usr/local/bin/
    - rm lite_linux_amd64.tar.gz
  script:
    # Attach the current commit to its branch.
    - git checkout -b $CI_COMMIT_REF_NAME

    # Push code changes to main Drupal.org repo.
    - mkdir -p ~/.ssh
    - echo "$GIT_DEPLOY_KEY" >> ~/.ssh/id_rsa
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 0700 ~/.ssh
    - chmod 0600 ~/.ssh/id_rsa
    - chmod 0644 ~/.ssh/known_hosts
    - git remote add drupalorg git@git.drupal.org:project/panopoly.git
    - git push drupalorg $CI_COMMIT_REF_NAME

    # Do subtree split and push.
    - php composer.phar install
    - ./vendor/bin/robo subtree-split --push
  only:
    refs:
      - 8.x-2.x
    variables:
      - $GIT_DEPLOY_KEY
      - $SSH_KNOWN_HOSTS

