<?php

include_once('panopoly_magic.features.inc');

/**
 * Implementation of hook_form_alter()
 */
function panopoly_magic_form_alter(&$form, $form_state, $form_id) {

  /**
   * Globally remove the "Cancel" button from Panel pane edit forms
   */
  if (strpos($form_id, 'content_type_edit_form')) { 
    $form['buttons']['cancel']['#access'] = FALSE;
  }

  /**
   * Add a custom preview to the content type edit form and style edit form. This is applied in all cases, except for cases where
   * we are customizing an entity (i.e. fieldable panels panes) because we cannot reliable regenerate a preview without saving.
   */
  if ((strpos($form_id, '_content_type_edit_form') && $form_id != 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form') || $form_id == 'panels_edit_style_type_form') {

    // Start the magic
    $pane = $form_state['pane'];
    $display = $form_state['display'];
    ctools_include('plugins', 'panels');
    ctools_include('content');

    // Determine the style
    if (strpos($form_id, '_content_type_edit_form')) {
      $style = (isset($pane->style['style'])) ? panels_get_style($pane->style['style']) : NULL;
    }
    elseif ($form_id == 'panels_edit_style_type_form') {
      $style = ($form_state['rebuild'] && $form_id == 'panels_edit_style_type_form') ? panels_get_style($form_state['values']['style']) : panels_get_style($form_state['style']);
    }
    else {
      $style = NULL;
    }

    // Determine the configuration
    // TODO - if a cleverer person can save the entity and get a vuuid, then we can pass that
    // as a "uuid:asds-adsa-dsad-adsd-adda-adssd" subtype and it all works wonderfully.
    $configuration = ($form_state['rebuild'] && strpos($form_id, 'content_type_edit_form')) ? $form_state['input'] : $pane->configuration;

    // Determine the content 
    $content = ctools_content_render($pane->type, $pane->subtype, $configuration);

    // Remove the clearfix for preview floating
    // TODO - investigate why Panels is putting this here in the first place
    if (isset($form['aligner_start'])) {
      $form['aligner_start']['#markup'] = str_replace('clearfix', '', $form['aligner_start']['#markup']);
    }

    // Create the preview fieldset
    if ($content) {
      $form['widget_preview'] = array(
        '#type' => 'fieldset',
        '#title' => 'Preview',
        '#attributes' => array('class' => array('widget-preview', 'widget-preview-single')),
        '#collapsible' => FALSE,
        '#weight' => -100,
      );
      $form['widget_preview']['preview'] = array(
        '#markup' => (!empty($style['render pane'])) ? theme($style['render pane'], array('content' => $content, 'pane' => $pane, 'display' => $display, 'style' => $style, 'settings' => $pane->style['settings'])) : theme('panels_pane', array('content' => $content, 'pane' => $pane, 'display' => $display)),
      );

      // Create the preview refresh button
      $form['buttons']['preview'] = array(
        '#type' => 'button',
        '#value' => t('Update Preview'),
        '#wizard type' => 'next',
        '#attributes' => array('style' => 'display: none', 'class' => array('widget-preview-button', 'ctools-use-ajax', 'ctools-auto-submit-click')),
      );

      // Autosubmit the form
      ctools_add_js('auto-submit');
      $form['#attributes']['class'][] = 'ctools-auto-submit-full-form';
    }
  }

  /**
   * Add customization to panel pane style form
   */
  if ($form_id == 'panels_edit_style_type_form') {

    // Unset options for which we have no need
    unset($form['style']['#options']['block']);
    unset($form['style']['#options']['rounded_corners']);
    unset($form['style']['#options']['naked']);

    // Better explain that "No Style" means "Default Pane Style"
    if (!empty($form['style']['#options']['default'])) {
      $form['style']['#options']['default'] = t('Default Pane Style');
    }

    // Improve the UI around region style selections
    if (!empty($form['style']['#options']['-1'])) {
      $form['style']['#options']['-1'] = t('Default Region Style');
      unset($form['style']['#options']['default']);
    }

    // Adding a fieldset around styling
    $form['style'] = array('style' => $form['style']);
    $form['style']['#type'] = 'fieldset';
    $form['style']['#title'] = t('Style Settings');
  }

  /**
   * Add customization to views panel pane settings form
   */
  if ($form_id == 'views_content_views_panes_content_type_edit_form') {

    // Get the configuration
    $conf = $form_state['conf'];

    // Add the content setting fieldset
    if (isset($form['exposed']) && count($form['exposed']) > 1) {
      $form['exposed']['#title'] = t('General Settings');
      $form['exposed']['#type'] = 'fieldset';
      $form['exposed']['#weight'] = -10;
    } 
    else {
      $form['exposed'] = array(
        '#type' => 'fieldset',
        '#title' => t('General Settings'),
        '#weight' => -30,
      );
    }

    // Better position context settings
    if (!empty($form['context'])) {
      $form['context_settings'] = array(
        '#type' => 'fieldset',
        '#title' => t('Context Settings'),
      );
      $form['context_settings']['context'] = $form['context'];
      unset($form['context']);
    }

    // Better position page settings
    if (!empty($form['use_pager'])) {
      $form['exposed']['use_pager'] = $form['use_pager'];
      $form['exposed']['pager_id'] = $form['pager_id'];
      unset($form['use_pager']);
      unset($form['pager_id']);
    }


    // Add a widget title setting if views allows this to be customized
    if (!empty($form['override_title'])) {
      $form['override_title_markup']['#access'] = FALSE;
      $form['override_title']['#access'] = FALSE;
      $form['override_title_text']['#access'] = FALSE;
      $form['exposed']['widget_title'] = array(
        '#field_prefix' => t('Title'),
        '#type' => 'textfield',
        '#size' => 30,
        '#weight' => -100,
        '#attributes' => (empty($conf['widget_title']) || empty($form_state['view']->display_handler->options['title'])) ? array('placeholder' => '<No Title>') : array(),
        '#default_value' => (isset($conf['widget_title'])) ? $conf['widget_title'] : $form_state['view']->display_handler->options['title'],
      );
    }

    // Adjust the sort options
    if (!empty($form['exposed']['sort_order'])) {
      $form['exposed']['sort_order']['#title'] = t('Sort order');
      $form['exposed']['sort_order']['#suffix'] = '<div class="clearfix"></div>';
    }
    if (!empty($form['exposed']['sort_by'])) {
      $form['exposed']['sort_by']['#prefix'] = '<div class="clearfix"></div>';
    }

    // Switch all exposed filters to use field_prefix display
    foreach($form['exposed'] as $filter => $filter_array) {
      if (!empty($form['exposed'][$filter]['#title']) && empty($form['exposed'][$filter]['#field_prefix'])) {
        $form['exposed'][$filter]['#field_prefix'] = $form['exposed'][$filter]['#title'];
        unset($form['exposed'][$filter]['#title']);
      }
    }

    // Move items per page wiget to widget area
    if (isset($form['items_per_page'])) {
      $form['items_per_page']['#field_prefix'] = $form['items_per_page']['#title'];
      $form['items_per_page']['#title'] = '';
      $form['items_per_page']['#weight'] = -90;
      $form['exposed']['items_per_page'] = $form['items_per_page'];
      unset($form['items_per_page']);
    }

    // Update field setting options
    if (isset($form['fields_override'])) {
      $form['fields_override']['#title'] = t('Field Settings');
      $form['fields_override']['#collapsible'] = FALSE;
      foreach($form['fields_override'] as &$field) {
        if (is_array($field)) {
          $field['#title'] = t('Display') . ' ' . $field['#title'];
        }
      }
    }

    // Determine if this is a node view.
    $view_handler = $form_state['view']->display_handler;
    $node_view = ($view_handler->options['row_plugin'] == 'node' && in_array($view_handler->options['style_plugin'], array('default'))) ? TRUE : FALSE;

    if ($node_view == FALSE) {
      if (empty($conf['view_settings'])) {
        $conf['view_settings'] = 'fields';
      }

      // Create the fieldset and the settings selection form.
      $form['display_type'] = array(
        '#type' => 'fieldset',
        '#title' => t('Display Type'),
        // Make the weight of this fieldset dependent on the general settings fieldset.
        '#weight' => $form['exposed']['#weight'] + 1,
      );

      $form['display_type']['view_settings'] = array(
        '#type' => 'radios',
        // '#title' => t('Display Type'),
        '#default_value' => $conf['view_settings'],
        '#options' => array(
          'fields' => t('Fields'),
          'nodes' => t('Content'),
        ),
      );

      // Update the field overrides to be dependent on the view settings selection.
      $form['fields_override']['#states'] = array(
        'visible' => array(
          ':input[name="view_settings"]' => array('value' => 'fields'),
        ),
      );
    }

    // Add the style setting fieldset in any case
    $form['content_settings'] = array(
      '#type' => 'fieldset',
      '#title' => 'Content Settings',
    );

    // Add specific style options.
    $form['content_settings']['view_mode'] = array(
      '#type' => 'radios',
      '#options' => panopoly_core_view_mode_options(),
      '#default_value' => $conf['view_mode'] ? $conf['view_mode'] : 'teaser',
      '#states' => array(
        'visible' => array(
          ':input[name="view_settings"]' => array('value' => 'nodes'),
        ),
      ),
    );  

    // Override context settings if there is only one option.
    if (!empty($form['context_settings']['context'])) {
      $show_fieldset = FALSE;
      foreach (element_children($form['context_settings']['context']) as $child) {
        // If the element has only one option, just hide the field.
        if (empty($form['context_settings']['context'][$child]['#options']) || count($form['context_settings']['context'][$child]['#options']) < 2) {
          $form['context_settings']['context'][$child]['#type'] = 'hidden';
        }
        else {
          // We should show the fieldset if at least one sub element has multiple options.
          $show_fieldset = TRUE;
        }
      }

      if (empty($show_fieldset)) {
        $form['context_settings']['#type'] = 'hidden';
      }
    }

    // Add a custom submit handler
    $form['#submit'][] = 'panopoly_magic_views_view_mode_pane_submit';
  }

  /**
   * Override default entity view mode behavior for fieldable panel panes.
   */
  if ($form_id == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form') {

    // Handle the view mode
    $view_mode = $form['view_mode'];
    unset($form['view_mode']);

    // Remove "tokens" from the list of available view modes.
    if (!empty($view_mode['#options']['token'])) {
      unset($view_mode['#options']['token']);
    }

    // If we're left with only one option, don't display the dropdown.
    if (count($view_mode['#options']) < 2) {
      $view_type = reset(array_keys($view_mode['#options']));
      $view_mode = array(
        '#type' => 'value',
        '#value' => $view_type,
      );
    }

    // Re-insert the view mode selection under the "General settings" fieldset.
    $form['widget_settings']['view_mode'] = $view_mode;
  }

  /**
   * Globally make sure that all options are inside a fieldset. Currently just supporting a known list
   * of forms, but persumably this can be applied to all items
   */
  if (in_array($form_id, array('panopoly_search_search_box_content_type_edit_form', 'menu_block_menu_tree_content_type_edit_form', 'ctools_node_content_content_type_edit_form'))) {

    // Grab child elements and create the fieldset.
    $children = element_children($form);
    if (count($children) > 1) {
      $form['general_settings'] = array(
        '#type' => 'fieldset',
        '#title' => t('General Settings'),
        '#weight' => -30,
      );

      // Move all elements which aren't fieldsets or the submit buttons into the general settings fieldset.
      foreach ($children as $child) {
        if (!empty($form[$child]['#type']) && $form[$child]['#type'] != 'fieldset' && $child != 'buttons') {
          $form['general_settings'][$child] = $form[$child];
          unset($form[$child]);
        }
      }
    }
  }
}

/**
 * Custom submit handler to save panels pane configuration for styling
 */
function panopoly_magic_views_view_mode_pane_submit(&$form, &$form_state) {
  $form_state['conf']['view_mode'] = (isset($form_state['values']['view_mode'])) ? $form_state['values']['view_mode'] : NULL;

  // Set the $conf['widget_title'] value. We need to do this a
  // little funky since sometimes it comes inside of $form_state['values']
  // and sometimes it doesn't. 
  if (isset($form_state['values']['exposed']['widget_title'])) {
    $form_state['conf']['widget_title'] = $form_state['values']['exposed']['widget_title'];
  }
  elseif (isset($form_state['values']['widget_title'])) {
    $form_state['conf']['widget_title'] = $form_state['values']['widget_title'];
  }
  else {
    $form_state['conf']['widget_title'] = NULL;
  }

  // Set the $conf['items_per_page'] value. We need to do this a
  // little funky since sometimes it comes inside of $form_state['values']
  // and sometimes it doesn't. 
  if (isset($form_state['values']['exposed']['items_per_page'])) {
    $form_state['conf']['items_per_page'] = $form_state['values']['exposed']['items_per_page'];
  }
  elseif (isset($form_state['values']['items_per_page'])) {
    $form_state['conf']['items_per_page'] = $form_state['values']['items_per_page'];
  }
  else {
    $form_state['conf']['items_per_page'] = NULL;
  }

  // Save the view settings field is present in the data.
  if (isset($form_state['values']['view_settings'])) {
    $form_state['conf']['view_settings'] = $form_state['values']['view_settings'];
  }
}

/**
 * Implementation of hook_views_pre_render()
 */
function panopoly_magic_views_pre_render(&$view) {
  if (isset($view->display_handler->options['pane_conf'])) {
    $conf = $view->display_handler->options['pane_conf'];

    // Set the view title depending on where it comes. We do this a little
    // funky since sometimes it comes inside of $form_state['values'] and 
    // sometimes it doesn't.
    if (isset($conf['widget_title']) || isset($conf['exposed']['widget_title'])) {
      $view->display_handler->options['title'] = (isset($conf['exposed']['widget_title'])) ? $conf['exposed']['widget_title'] : $conf['widget_title']; 
      $view->build_info['title'] = (isset($conf['exposed']['widget_title'])) ? $conf['exposed']['widget_title'] : $conf['widget_title']; 
    }

    // Determine that this was previously a field view, which has been overridden to a node view in the pane config.
    if (!empty($conf['view_settings']) && $conf['view_settings'] == 'nodes' && empty($view->style_plugin->row_plugin->nodes)) {
     
      // Reconstruct the nodes array which a node row style expects.
      if (!empty($view->result)) {
        $nids = array();
        foreach ($view->result as $result) {
          $nids[] = $result->nid;
        }
        $nodes = node_load_multiple($nids);
      }

      // Change the row plugin.
      if (!empty($nodes)) {
        $view->style_plugin->row_plugin = views_get_plugin('row', 'node');
        $view->style_plugin->row_plugin->view =& $view;
        $view->style_plugin->row_plugin->display =& $view->display_handler->display;
        $view->style_plugin->row_plugin->field_alias = 'nid';
        $view->style_plugin->row_plugin->nodes = $nodes;
      }
    }

    // Set the view mode
    if (isset($conf['view_mode'])) {
      $view->style_plugin->row_plugin->options['view_mode'] = $conf['view_mode'];
    }
  }
}

/**
 * Implementation of hook_module_implements_alter()
 */
function panopoly_magic_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    $group = $implementations['panopoly_magic'];
    unset($implementations['panopoly_magic']);
    $implementations['panopoly_magic'] = $group;
  }
}


/**
 * Preprocess the panels_ipe_toolbar to change text for IPE buttons
 */
function panopoly_magic_preprocess_panels_ipe_toolbar(&$vars) {
  foreach($vars['buttons'] as $panel_context_id => $panel_context) {
    foreach($panel_context as $button_name => $button) {
      switch($button_name) {
        case 'panels-ipe-startedit':
          $vars['buttons'][$panel_context_id][$button_name]['#title'] = 'Customize this page';
          break;
        case 'panels-ipe-change-layout':
          $vars['buttons'][$panel_context_id][$button_name]['#title'] = 'Change this layout';
          break;
      }
    }
  }
}

/**
 * Preprocess the panels_add_content_modal() function to add the HTML for the preview
 */
function panopoly_magic_preprocess_panels_add_content_modal(&$vars) {
  // Generate the pane preview
  if (!empty($vars['categories'][$vars['category']]['content'])) {
    foreach($vars['categories'][$vars['category']]['content'] as &$plugin) {
      $pane = panels_new_pane($plugin['type_name'], $plugin['subtype_name'], TRUE);
      $display = $vars['renderer']->display;
      $context = $vars['renderer']->display->context;
      $args = $vars['renderer']->display->args;
      $incoming_content = $vars['renderer']->display->incoming_content;
      $keywords = (!empty($vars['renderer']->display->keywords)) ? $vars['renderer']->display->keywords : array();
      if ($content = ctools_content_render($pane->type, $pane->subtype, $pane->configuration, $keywords, $args, $context, $incoming_content)) {
        $plugin['preview'] = theme('panels_pane', array('content' => $content, 'pane' => $pane, 'display' => $display));
      }
    }
  }
}

/** 
 * Process the panels_add_content_modal() to adjust the markup to present the preview
 */
function panopoly_magic_process_panels_add_content_modal(&$vars) {
  $content = !empty($vars['categories'][$vars['category']]['content']) ? $vars['categories'][$vars['category']]['content'] : array();

  // If no category is selected or the category is empty or our special empty
  // category render a 'header' that will appear instead of the columns.
  if (empty($vars['category']) || empty($content) || $vars['category'] == 'root') {
    // Nothing to do since there is no preview
  }
  else {
    $titles = array_keys($content);
    natcasesort($titles);
    $col_size = count($titles) / $vars['column_count'];

    // Zero out the existing column data
    $count = 0;
    foreach ($titles as $title) {
      $which = floor($count++ / $col_size) + 1;
      $vars['columns'][$which] = '';
    }

    // Readd the column data with our preview functionality
    $count = 0;
    foreach ($titles as $title) {
      $which = floor($count++ / $col_size) + 1;
      $content[$title]['title'] = 'Add';
      $vars['columns'][$which] .= '<fieldset class="widget-preview"><legend><div class="widget-preview-title">' .  theme('panels_add_content_link', array('renderer' => $vars['renderer'], 'region' => $vars['region'], 'content_type' => $content[$title])) . '</div><span class="fieldset-legend">' . $title . '</span></legend><div class="fieldset-wrapper">' . $content[$title]['preview'] . '</div></fieldset>';
    }
  }
}
