<?php

/**
 * @file
 * Hook implementations for Panopoly Images.
 */

/**
 * Implements hook_preprocess_image_style().
 */
function panopoly_images_preprocess_image_style(&$vars) {
  // Attach our CSS and Javascript when one of our image styles is used.
  $panopoly_image_styles = [
    'panopoly_images_original',
    'panopoly_images_full',
    'panopoly_images_half',
    'panopoly_images_quarter',
    'panopoly_images_featured',
    'panopoly_images_square',
    'panopoly_images_thumbnail',
  ];
  if (in_array($vars['style_name'], $panopoly_image_styles)) {
    $vars['#attached']['library'][] = 'panopoly_images/panopoly_images';
  }
}
