<?php

include_once('panopoly_core.features.inc');

/**
 * Implementation of hook_init()
 */
function panopoly_core_init() {

  // Set the current page title in the breadcrumb
  $breadcrumb = drupal_get_breadcrumb();
  if (count($breadcrumb) && drupal_get_title()) {
    $breadcrumb[] = drupal_get_title();

    // If it is the homepage, remove the breadcrumb
    if (drupal_is_front_page()) {
      $breadcrumb = array();
    }
    drupal_set_breadcrumb($breadcrumb);
  }
}

/**
 * Implements hook_apps_servers_info()
 */
function panopoly_core_apps_servers_info() {
  $profile = variable_get('install_profile', 'panopoly');
  $info =  drupal_parse_info_file(drupal_get_path('profile', $profile) . '/' . $profile . '.info');
  return array(
    'panopoly_apps' => array(
      'title' => 'Panopoly Apps',
      'description' => 'Apps for Panopoly',
      'manifest' => (empty($info['version']) || $info['version'] == '7.x-1.x-dev') ? 'http://apps.getpantheon.com/panopoly-apps-dev' : 'http://apps.getpantheon.com/panopoly-apps',
    ),
  );
}


/**
 * Implements hook_date_format_types()
 */
function panopoly_core_date_format_types() {
  return array(
    'panopoly_time' => t('Time'),
    'panopoly_day' => t('Day'),
  );
}

/**
 * Implements hook_date_formats().
 */
function panopoly_core_date_formats() {
  $formats = array();

  // Time
  $formats[] = array(
    'type' => 'panopoly_time',
    'format' => 'g:ia',
    'locales' => array(),
  );

  // Day
  $formats[] = array(
    'type' => 'panopoly_day',
    'format' => 'F j, Y',
    'locales' => array(),
  );

  return $formats;
}

