panopoly_admin.settings:
  type: config_object
  label: 'Panopoly Admin settings'
  mapping:
    layouts:
      type: sequence
      label: 'Layouts'
      sequence:
        - type: boolean
    blocks:
      type: sequence
      label: 'Blocks'
      sequence:
        - type: boolean