<?php

include_once('panopoly_users.features.inc');

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function panopoly_users_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
} 

/**
 * Implementation of hook_menu_alter()
 */
function panopoly_users_menu_alter(&$items) {

  // Remove tabs from user login page
  $items['user/login']['type'] = MENU_CALLBACK;
  $items['user/register']['type'] = MENU_CALLBACK;
  $items['user/password']['type'] = MENU_CALLBACK;
}

/**
 * Implementation of hook_form_alter()
 */
function panopoly_users_form_alter(&$form, $form_state, $form_id) {

  // Add a create account link below the username
  if ($form_id == 'user_login' && variable_get('user_register')) {
    $form['name']['#description'] .= '<br>' . t('If you don\'t have an username, !create.', array('!create' => l('create an account', 'user/register')));
  }

  // Add the request password link below the password
  if ($form_id == 'user_login') {
    $form['pass']['#description'] .= '<br>' . t('If you forgot your password, !request.', array('!request' => l('request a new password', 'user/password')));
  }
}
